// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4BBmH1NH9oUxT4gu8sPxms2ayHJ5olIQ',
    appId: '1:589856481585:web:e8cf1cd58ea4310b6c5010',
    messagingSenderId: '589856481585',
    projectId: 'youconnect-dfa94',
    authDomain: 'youconnect-dfa94.firebaseapp.com',
    storageBucket: 'youconnect-dfa94.appspot.com',
    measurementId: 'G-L9GD70W8V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1wRgWofo_nyGLEga6DAqJOgFi1fT9qOw',
    appId: '1:589856481585:android:2945a5218fd991e96c5010',
    messagingSenderId: '589856481585',
    projectId: 'youconnect-dfa94',
    storageBucket: 'youconnect-dfa94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWTabgqCje6L5UaeYClbcKqN1cmL9hVFg',
    appId: '1:589856481585:ios:5faf0b0efd9bf1a26c5010',
    messagingSenderId: '589856481585',
    projectId: 'youconnect-dfa94',
    storageBucket: 'youconnect-dfa94.appspot.com',
    iosBundleId: 'com.example.infoProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWTabgqCje6L5UaeYClbcKqN1cmL9hVFg',
    appId: '1:589856481585:ios:238617796b79b8916c5010',
    messagingSenderId: '589856481585',
    projectId: 'youconnect-dfa94',
    storageBucket: 'youconnect-dfa94.appspot.com',
    iosBundleId: 'com.example.infoProfile.RunnerTests',
  );
}
